[build]
  base = "."
  publish = "client/dist"
  command = "cd client && npm install && npm run build && cd ../netlify/functions && npm install"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  external_node_modules = ["@prisma/client"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"
  DATABASE_URL = "file:./data/prod.db"